some lists must not be immutable
otherwise serialization will fail

java.lang.UnsupportedOperationException: Refusing to marshal java.util.ImmutableCollections$ListN for security reasons

fixes regression from ba7ac59488b1a0a7a1b790b086c584eea95b8488